<?php /** @var $block \Pre\News\Block\FeedList */ ?>
<h1><?php echo __('Current News') ?></h1>
<ul>
    <?php /** @var $feed \Pre\News\Model\Feed */ ?>
    <?php foreach ($block->getFeeds() as $feed): ?>
        <li>
            <h3>
                <a href="<?php echo $feed->getUrl() ?>"><?php echo $feed->getFeedName() ?></a>
            </h3>

            <ul>
                <?php $rssData = $block->getRssContent($feed->getFeedUrl()); ?>
                <?php foreach ($rssData as $rss): ?>
                    <li>
                        <a href="<?php echo $rss['href'] ?>"><b><?php echo $rss['title0'] ?></b><?php echo (!empty($rss['title1'])) ?  ": " . $rss['title1'] : "" ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
</ul>
